### ISSUE TITLE
Modifying this to work with the HyperX Cloud 2 Headset.

### ISSUE THREAD

**Issue by mrmatt91** [crazyklatsch/Arctis7_BatteryReader#1]
Hello, I'm trying to adapt what you've done here to work with my Cloud 2 headset but I just can't seem to get the proper addresses for the battery information. What tool did you use to sniff the USB requests? Thanks!

**Comment by crazyklatsch** [comment]
Hey, i found out about the address in some forum post where someone else tried something similar and a Steelseries developer answered what to find at which address.
