### ISSUE TITLE
Arctis 1 Wirless causes "System.IO.IOException" in mscorlib.dll

### ISSUE THREAD

**Issue by julian-ben** [crazyklatsch/Arctis7_BatteryReader#2]
I tried converting this into an Arctis 1 Wireless compatible Program. I found that you need to change the PID and the VID for the Headset, which are PID 4787, VID 4152 for the Arctis 1. But now it causes an "System.IO.IOException" in mscorlib.dll when trying to write the bytes. Do you know why?

**Comment by crazyklatsch** [comment]
Unfortunatly, i think i can't help you with that :/
If i remember correctly the report buffer had to be of a certain length for it to work with the Arctis7, so maybe you have to get the Buffer-lengths right. Also i don't know if the address for the battery status is the same for the Arctis 1.

**Comment by crazyklatsch** [comment]
But maybe try this fork of my repo from cfazilleau:
https://github.com/cfazilleau/Arctis_BatteryReader
In the readme it sais support for the Arctis 1 Wireless

**Comment by julian-ben** [comment]
Same problem even after recompiling MightyHID

**Comment by julian-ben** [comment]
but in the fork the error moved to System.Private.CoreLib.dll

**Comment by crazyklatsch** [comment]
closing, because this does not concern the arctis 7
